// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isProd = process.env.NODE_ENV === "production";
const sqliteDevUrl = "file:./dev.db";
const datasourceUrl = process.env.DATABASE_URL || (isProd ? undefined : sqliteDevUrl);

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: datasourceUrl,
  },
});
